---
source:
  path: ./
  # git:
  #   url: https://framagit.org/rdeville-public/programs/dotgit-sync-templates
  #   ref: v0.0.0
name: dotgit-sync-templates
description: >-
  Repository of templated files to used in combination with
  [dotgit-sync](https://framagit.org/rdeville-public/programs/dotgit-sync)
maintainers:
  - name: Romain Deville
    mail: code+dotgit-sync-templates@romaindeville.fr
gitignore:
  templates:
    - base
    - python
    - javascript
    - jsonnet
licenses:
  copyright:
    owner: Romain Deville
    email: code@romaindeville.fr
  main: MIT
  others:
    - BEERWARE
templates:
  - common
statics:
  - common

# Everything below is only used as variables in templates
code_of_conduct:
  abuse: abuse+dotgit-sync-templates@romaindeville.fr
extra:
  maintainers:
    Romain Deville:
      socials:
        Website:
          alt: https://romaindeville.fr
          url: https://romaindeville.fr
        Github:
          alt: "@rdeville"
          url: https://github.com/rdeville
        Gitlab:
          alt: "@r.deville"
          url: https://gitlab.com/r.deville
        Framagit:
          alt: "@rdeville"
          url: https://framagit.org/rdeville
  repo:
    server: https://framagit.org/
    namespace: rdeville-public/programs
