---
# DotGit Sync Configuration
# ------------------------------------------------------------------------------
dotgit:
  source:
    # Use itself as this repo is the one that store my templates
    path: ./
    # If used from another repos, use `git` key below
    # git:
    #   url: https://framagit.org/rdeville-public/programs/dotgit-sync-templates
    #   ref: vX.Y.Z
  yaml:
    merge: only
    only:
      - .pre-commit-config.yaml
      - gitlab-ci.yaml

# Repos description
# ------------------------------------------------------------------------------
name: DotGit Sync Templates
description: |-
  Repository of templated files to used in combination with
  [dotgit-sync](https://framagit.org/rdeville-public/programs/dotgit-sync) to
  ease management of "dotfiles" in git repository (such as `.gitignore`,
  `.pre-commit-config.yaml`, `LICENSE`, `packages.json`, etc.).
licenses:
  date:
    first_year: "2024"
  copyright:
    owner: Romain Deville
    email: code@romaindeville.fr
  primary: MIT
  secondaries:
    - BEERWARE
maintainers:
  - name: Romain Deville
    mail: code@romaindeville.fr
gitignore:
  templates:
    - base
statics:
  - base
  - base-ci-gitlab
  - base-pre-commit
  - commitlint-pre-commit
  - markdown
  - markdown-pre-commit
  - markdown-ci-gitlab
templates:
  - base
  - nix

# Everything below is only used as variables in templates
# ------------------------------------------------------------------------------
code_of_conduct:
  abuse: abuse+code@romaindeville.fr
extra:
  maintainers:
    Romain Deville:
      socials:
        Website:
          alt: &website https://romaindeville.fr
          url: *website
        Github:
          alt: "@rdeville"
          url: https://github.com/rdeville
        Gitlab:
          alt: "@r.deville"
          url: https://gitlab.com/r.deville
        Framagit:
          alt: "@rdeville"
          url: https://framagit.org/rdeville
  repo:
    url: https://framagit.org/rdeville-public/programs/dotgit-sync-templates
    slug: dotgit-sync-templates
