default_stages:
  - pre-commit

repos:
    # General pre-commit applied every times
    # ------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        # Prevents giant files from being committed.
      - id: check-added-large-files
        # Removes utf-8 byte order marker.
      - id: fix-byte-order-marker
        # Checks for files that would conflict in case-insensitive filesystems.
      - id: check-case-conflict
        # Checks for files that contain merge conflict strings.
      - id: check-merge-conflict
        # Checks for symlinks which do not point to anything.
      - id: check-symlinks
        # Detects the presence of private keys.
      - id: detect-private-key
        # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer
        # Prevents addition of new git submodules.
      - id: forbid-new-submodules
        # Forbids any submodules in the repository
      - id: forbid-submodules
        # Don't commit to branch
      - id: no-commit-to-branch
        # Trims trailing whitespace.
      - id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.14.0
    hooks:
      - id: commitlint
        additional_dependencies:
          - gitmojis
        stages:
          - commit-msg
