# BEGIN DOTGIT-SYNC BLOCK MANAGED YAML_MERGED
Lint Markdown:
  image: alpine:latest
  stage: lint
  before_script:
  - apk add --update --no-cache git nodejs npm
  - npm install markdownlint-cli
  script:
  - npx markdownlint
  - npx markdownlint-cli ./
  rules:
  - when: always
  - if: $CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: never
# END DOTGIT-SYNC BLOCK MANAGED YAML_MERGED
