---
"Validate OpenTofu":
  image: alpine:latest
  stage: lint
  before_script:
    - apk add --update --no-cache
       curl
    - curl
        --proto '=https'
        --tlsv1.2
        -fsSL
        https://get.opentofu.org/install-opentofu.sh
        -o install-opentofu.sh
    - chmod +x install-opentofu.sh
    - ./install-opentofu.sh --install-method apk
    - rm -f install-opentofu.sh
    - tofu init -backend=false
  script:
    - tofu validate
  rules:
    # Do Not run when called from upstream CI as its DGS template update
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
      # Always run this job to ensure commit follow specific syntax as soon as
      # possible
    - when: always
